[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[dev]
  framework = "vite"
  command = "npm run dev"
  targetPort = 5173
  port = 8888

[context.production.environment]
  TMDB_API_KEY = "9685844985a834f65cf54ae1f7fb497a"
  TMDB_READ_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5Njg1ODQ0OTg1YTgzNGY2NWNmNTRhZTFmN2ZiNDk3YSIsIm5iZiI6MTQ1MTk0MzIxNS4wODQsInN1YiI6IjU2OGFlNTJlOTI1MTQxMmU1MjAyYTNjOSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.cvIpkJoyJWi6M1gDfZpRJfgiM7w0SOcbH3R-1TYVgic"
  PORT = "5174"
  DEFAULT_REGION = "US"
  CACHE_TTL_SECONDS = "300"
  ASTRA_DB_KEYSPACE = "movies2026"
  ASTRA_BOARDGAME_KEYSPACE = "boardgames"
  ASTRA_DB_APPLICATION_TOKEN = "AstraCS:wKkNJQCWNUZgebJyJBFNqRJC:c237b21726410918a4c6690e8e4f3e9f77086105dfbb4e5b5afc4e419a1149cc"
  ASTRA_DB_API_ENDPOINT = "https://59331a83-679d-4b30-a498-835c06d06538-us-east-2.apps.astra.datastax.com"
  OPENAI_API_KEY = "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"
  GOOGLE_API_KEY = "AIzaSyBo4GFEbu7P5PC6H0guqKzJ0zXY6HkALf8"
  ASTRA_INTERSECT_APPLICATION_TOKEN = "AstraCS:CSLdbRvOfwhMlFeeaRYEAbYZ:be31ebd777822fafd297c977dfd71ae7f5ff61d498b63679851b29c749054a8c"
  ASTRA_INTERSECT_ENDPOINT = "https://2bf19489-91db-4c11-ba2d-76e4671a2024-us-east-2.apps.astra.datastax.com"

